import configparser

_config = configparser.ConfigParser()
_config.read('Config/config.ini')

# Global constants loaded from the config file
AWS_REGION = _config['DEFAULT']['AWS_REGION']
MODEL_ID = _config['DEFAULT']['MODEL_ID']
IMAGE_GENERATION_MODEL_UD = _config['DEFAULT']['IMAGE_GENERATION_MODEL_UD']
EMBEDDING_MULTIMODAL_MODEL_ID = _config['DEFAULT']['EMBEDDING_MULTIMODAL_MODEL_ID']
EMBEDDING_TEXT_MODEL_ID = _config['DEFAULT']['EMBEDDING_TEXT_MODEL_ID']
IMAGE_PATH = _config['DEFAULT']['IMAGE_PATH']
OUTPUT_PATH = _config['DEFAULT']['OUTPUT_PATH']
OPENSEARCH_HOST = _config['DEFAULT']['OPENSEARCH_HOST']
OPENSEARCH_PORT = _config['DEFAULT'].getint('OPENSEARCH_PORT')
MULTIMODAL_INDEX_NAME = _config['DEFAULT']['MULTIMODAL_INDEX_NAME']
TEXT_INDEX_NAME = _config['DEFAULT']['TEXT_INDEX_NAME']
MAX_EMBEDDING_IMAGE_SIZE = _config['DEFAULT'].getint('MAX_EMBEDDING_IMAGE_SIZE')
MAX_EMBEDDING_IMAGE_DIMENSIONS = _config['DEFAULT'].getint('MAX_EMBEDDING_IMAGE_DIMENSIONS')
MAX_INFERENCE_IMAGE_SIZE = _config['DEFAULT'].getint('MAX_INFERENCE_IMAGE_SIZE')
MAX_INFERENCE_IMAGE_DIMENSIONS = _config['DEFAULT'].getint('MAX_INFERENCE_IMAGE_DIMENSIONS')
MAX_CHAT_IMAGE_SIZE = _config['DEFAULT'].getint('MAX_CHAT_IMAGE_SIZE')
MAX_CHAT_IMAGE_DIMENSIONS = _config['DEFAULT'].getint('MAX_CHAT_IMAGE_DIMENSIONS')
JPEG_SAVE_QUALITY = _config['DEFAULT'].getint('JPEG_SAVE_QUALITY')
DEFAULT_IMAGE_WIDTH = _config['DEFAULT'].getint('DEFAULT_IMAGE_WIDTH')
DEFAULT_IMAGE_HEIGHT = _config['DEFAULT'].getint('DEFAULT_IMAGE_HEIGHT')
AWS_LAMBDA_FUNCTION_NAME = _config['DEFAULT']['AWS_LAMBDA_FUNCTION_NAME']
MAX_OUTPUT_LENGTH = _config['DEFAULT'].getint('MAX_OUTPUT_LENGTH')
HANDLE_DOCUMENT_TO_TEXT_IN_CODE = _config['DEFAULT'].getboolean('HANDLE_DOCUMENT_TO_TEXT_IN_CODE')
MIN_RETRY_WAIT_TIME = _config['DEFAULT'].getint('MIN_RETRY_WAIT_TIME')
MAX_RETRY_WAIT_TIME = _config['DEFAULT'].getint('MAX_RETRY_WAIT_TIME')
MAX_TOKENS = _config['DEFAULT'].getint('MAX_TOKENS')
MAX_LOOPS = _config['DEFAULT'].getint('MAX_LOOPS')
MAX_WORKERS = _config['DEFAULT'].getint('MAX_WORKERS')
MIN_CHUNK_LENGTH = _config['DEFAULT'].getint('MIN_CHUNK_LENGTH')
MAX_CHUNK_LENGTH = _config['DEFAULT'].getint('MAX_CHUNK_LENGTH')
MAX_SEARCH_RESULTS = _config['DEFAULT'].getint('MAX_SEARCH_RESULTS')
MAX_ARCHIVE_RESULTS = _config['DEFAULT'].getint('MAX_ARCHIVE_RESULTS')
MAX_IMAGE_SEARCH_RESULTS = _config['DEFAULT'].getint('MAX_IMAGE_SEARCH_RESULTS')
DEFAULT_TEMPERATURE = _config['DEFAULT'].getfloat('DEFAULT_TEMPERATURE')
DEFAULT_SYSTEM_PROMPT = _config['DEFAULT']['DEFAULT_SYSTEM_PROMPT']
IMAGE_FORMATS = _config['DEFAULT']['IMAGE_FORMATS'].split(', ')
DOCUMENT_FORMATS = _config['DEFAULT']['DOCUMENT_FORMATS'].split(', ')
IMAGE_DESCRIPTION_PROMPT = _config['DEFAULT']['IMAGE_DESCRIPTION_PROMPT']
IMAGE_FILTER_PROMPT = _config['DEFAULT']['IMAGE_FILTER_PROMPT']
TOOLS_TIMEOUT = _config['DEFAULT'].getint('TOOLS_TIMEOUT')